<template>
    <div>
        <el-button
            size="mini"
            type=""
            @click="operate('edit')">编辑</el-button>
        <el-button
            size="mini"
            type="danger"
            @click="operate('delete')">删除</el-button>
    </div>
</template>
